### PR TITLE
replace SafeLineLoader to PythonSafeLoader

### LINKED ISSUE #753: Error loading on beta 2023.12.0b0 AttributeError: module 'homeassistant.util.yaml.loader' has no attribute 'SafeLineLoader'
AttributeError: module 'homeassistant.util.yaml.loader' has no attribute 'SafeLineLoader'

Issue with [#103609](https://github.com/home-assistant/core/pull/103609) the SafeLineLoader -> PythonSafeLoader rename.

--
Log details (ERROR)
Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 20:51:48 (2 occurrences)
Last logged: 20:54:09

  File "/usr/src/homeassistant/homeassistant/config.py", line 439, in async_hass_config_yaml
    config = await hass.loop.run_in_executor(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config.py", line 470, in load_yaml_config_file
    conf_dict = load_yaml(config_path, secrets)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 155, in load_yaml
    return parse_yaml(conf_file, secrets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 168, in parse_yaml
    return _parse_yaml(FastSafeLoader, content, secrets)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 198, in _parse_yaml
    yaml.load(content, Loader=lambda stream: loader(stream, secrets))  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 51, in get_single_data
    return self.construct_document(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 55, in construct_document
    data = self.construct_object(node)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 330, in _handle_mapping_tag
    nodes = loader.construct_pairs(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 330, in _handle_mapping_tag
    nodes = loader.construct_pairs(node)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 155, in construct_pairs
    value = self.construct_object(value_node, deep=deep)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/constructor.py", line 100, in construct_object
    data = constructor(self, node)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/yaml/loader.py", line 249, in _include_yaml
    return _add_reference(load_yaml(fname, loader.secrets), loader, node)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/dwains_dashboard/process_yaml.py", line 46, in load_yamll
    return loader.yaml.load(config_file, Loader=lambda stream: loader.SafeLineLoader(stream, secrets)) or OrderedDict()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/yaml/__init__.py", line 79, in load
    loader = Loader(stream)
             ^^^^^^^^^^^^^^
  File "/config/custom_components/dwains_dashboard/process_yaml.py", line 46, in <lambda>
    return loader.yaml.load(config_file, Loader=lambda stream: loader.SafeLineLoader(stream, secrets)) or OrderedDict()
                                                               ^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.util.yaml.loader' has no attribute 'SafeLineLoader'

### LINKED ISSUE #766: Deprecated method 'SafeLineLoader' will stop working n HA Core 2024.6
This is a rather new message in HA core n HA Core 2024.6 and dashboard 3.6.0 

2023-12-23 13:35:19.624 WARNING (MainThread) [homeassistant.helpers.frame] Detected that custom integration 'dwains_dashboard' uses deprecated 'SafeLineLoader' instead of 'PythonSafeLoader', which will stop working in HA Core 2024.6, at custom_components/dwains_dashboard/process_yaml.py, line 69: loader.SafeLineLoader.add_constructor("!include", _include_yaml), please create a bug report at https://github.com/dwainscheeren/dwains-lovelace-dashboard/issues

### PR DESCRIPTION
**Pull request by linuxmaniac**
fixes #753 and fixes #766

### CODE REVIEW

**Comment by dwainscheeren** [comment]
Is this working?

**Comment by linuxmaniac** [comment]
Yes, I manually patched and works fine AFAIC

**Comment by FSHelgeland** [comment]
Will there be an update trough HACS on this?
